{{- range .Values.projects }}
{{- if .enabled }}
{{- $name := .name }}
{{- $path := .path }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    istio-injection: enabled
...
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $name }}
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/t-ash0410/try-k8s.git"
  destinations:
    - namespace: {{ $name }}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
...
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
spec:
  destination:
    namespace: {{ $name }}
    server: https://kubernetes.default.svc
  project: {{ $name }}
  source:
    path: {{ $path }}
    repoURL: https://github.com/t-ash0410/try-k8s.git
    targetRevision: main
  syncPolicy:
    automated: {}
...
{{- end }}
{{- end }}
