{{- range .Values.projects }}
{{- if .enabled }}
{{- $name := .name }}
{{- $path := .path }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
spec:
  destination:
    namespace: defalut
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ $path }}
    repoURL: https://github.com/t-ash0410/try-k8s.git
    targetRevision: main
  syncPolicy:
    automated: {}
...
{{- end }}
{{- end }}
