---
# Source: projects/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
spec:
  destination:
    namespace: defalut
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/argocd/resources/httpd
    repoURL: https://github.com/t-ash0410/try-k8s.git
    targetRevision: main
  syncPolicy:
    automated: {}
...
---
# Source: projects/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: defalut
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/argocd/resources/nginx
    repoURL: https://github.com/t-ash0410/try-k8s.git
    targetRevision: main
  syncPolicy:
    automated: {}
...
